version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/testsimplify
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: changeme
      EMAIL_SERVER: smtp://mailhog:1025
      EMAIL_FROM: "TestSimply <noreply@testsimplify.local>"
    depends_on:
      - db
      - mailhog
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testsimplify
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
volumes:
  postgres-data:
